### PR TITLE
Simple Theme integrated

### PR DESCRIPTION
**Pull request by ja0b**
This theme https://wow.curseforge.com/projects/tidyplates-simple is now integrated to TidyPlatesContinuedm I had to do a few changes but it seems it's all working :)

### CODE REVIEW

**Comment by Luxocracy** [comment]
I'll merge this, but I'm gonna have to fix a few things I noticed aren't working because of missing widgets. I noticed it in the Renaitre theme as well but it seemed to still be working at that time. However this one won't show debuffs if you have the absorb widget toggled on.

**Comment by ja0b** [comment]
didn't notice that, thanks! I'll check your changes to apply them to the other 2 themes I'm migrating now. 👍

**Comment by Luxocracy** [comment]
Well it has to do with the absorb widget added by @AHigi, as such they won't have it defined.

In the case of this theme specifically, it had no widgets defined at all. I'll look into it some more because the only widget causing issue was the absorb one, most of the others seemed to still show up(with the exception of personal resource/combo points). So it might just be a default value not having been created for the absorb widget, even though a default position of it would probably look completely out of place.

**Comment by ja0b** [comment]
Yes, you're right, it has to be with the widgets, just added the same widgets values from BlizzardPlates and I'm now seeing the debuffs. 

Still, I need to do some more digging around to understand how the widget thing works.

**Comment by ja0b** [comment]
@Luxocracy leave this with me, I know how to fix it now :) just something I noticed, as far as I know, the health bar on totems is not a thing anymore, can we remove the "Show Totem Art" widget? 

I still need to see how these work:

-- WidgetConfig.DebuffWidgetPlus
-- WidgetConfig.RangeWidget 
--WidgetConfig.ThreatLineWidget 
-- WidgetConfig.ThreatWheelWidget

**Comment by ja0b** [comment]
Ok @Luxocracy too late 😂 the release it's out!
Thanks!!

**Pull request merged**
