### PR TITLE
Slim & Alvara Themes added

### PR DESCRIPTION
**Pull request by ja0b**

### CODE REVIEW

**Comment by ja0b** [comment]
@Luxocracy Please let me do it :) this is the first time I'm involved in a wow addon so I'm still in the learning curve, thanks for you clinic eye on the testing part, I'll update the PR later today 👍

**Comment by ja0b** [comment]
Ok, I've changed the positions to something that works, the _Slim Vertical_ theme is mean to work like that with debuffs, as currently, the addon doesn't have the option for vertical debuffs.

Doing these changes I've found a bug that I couldn't get fixed see this [http://recordit.co/M0pm9d7BME](http://recordit.co/M0pm9d7BME) using the _Slim Horizontal_ theme I cannot get in sync the castborder and the castnostop when I position one the other gets crazy and the other way around.

Also, I tried multiple things to see the absorb bar but I didn't manage to get it working. Could you have a look at this ? And just for curiosity could you share an image/gif of how the absorb bar is mean to work ?

Thanks! 👍

**Comment by Luxocracy** [comment]
Absorb bars not show up for you could be one of two reasons.
1. Your spec is using the wrong profile compare to what you are editing. Had this happen to me on my priest, it was set to tank instead of healer.
2. You are using the _Blizzlike_ option, and probably not even noticing that it happens because the unit with absorb on it has full health, meaning it's a really small line. Use the [overlay option](https://i.imgur.com/ITbVrcE.jpg?2) as it will be much clearer.
Oh, and also the absorb will only show on your current target.

I'll see if I can figure out whats going on with your castborders on the _Slim Horizontal_ theme.

**Comment by ja0b** [comment]
Just fixed the threatline alignment issues on the themes and also the absorb bars.

The issue I was having (http://recordit.co/M0pm9d7BME) it's fixed, this was some weird cache happeing on my machine.

The only thing is pending is the absorb bar for the _Slim Vertical_ theme,  as this is just horizontal for now, I couldn't fix it because I don't know how to pass a new variable to this: 

`WidgetConfig.AbsorbWidget = { anchor="LEFT", x = 28 , y = 4, h = 36, w = 6 }`

My idea was to pass something like "vertical" to AbsorbWidget and do something like this where required.

```
    if vertical == nil then 
        frame.Line:SetHorizTile(true)
    else frame.Line:SetVertTile(true) end

    if vertical == nil then
        frame.Line:SetTexture(art, "REPEAT", "REPEAT")
    else frame.Line:SetTexture(artVertical, "REPEAT", "REPEAT") end
```

If you can @Luxocracy continue with this, that would be great!!! 💯 
I realised that when the absorb was higher that the max health the absorb bar was getting crazy, that's fixed! 🎉 

And I added the required graphic for this 😃 

Thanks!

**Comment by Luxocracy** [comment]
Gonna merge this and apply the changes I've made. Making the absorb widget vertical was a lot more annoying then I thought it would be, a lot of weird issues... But I believe it is working correctly now.

**Pull request merged**
